---
- name: Déployer un serveur Apache
  hosts: webservers
  become: yes
  tasks:
    - name: Installer Apache
      apt:
        name: apache2
        state: present

    - name: Démarrer Apache
      service:
        name: apache2
        state: started
        enabled: yes
